jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        sudo add-apt-repository ppa:hvr/ghc
        sudo apt-get update
        sudo apt-get install ghc-8.6.5 cabal-install-3.0
        sudo update-alternatives --config opt-ghc
        sudo update-alternatives --config opt-cabal
      displayName: 'Prepare system'
    - script: |
        export PATH=/opt/ghc/bin:$HOME/.cabal/bin:$PATH
        cabal v2-update
        cabal v2-build
        cabal v2-exec which foundry
      displayName: 'Build'
  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - script: |
        brew install gtk+3 libffi pkgconfig
        export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH
        mkdir -p $HOME/.ghcup/bin && curl https://raw.githubusercontent.com/haskell/ghcup/master/ghcup > $HOME/.ghcup/bin/ghcup && chmod +x $HOME/.ghcup/bin/ghcup
        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
        ghcup install 8.6.5
        ghcup set 8.6.5
        ghcup install-cabal
      displayName: 'Prepare system'
    - script: |
        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
        export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH
        cabal v2-update
        cabal v2-build
        cabal v2-exec which foundry
      displayName: 'Build'
